// Loader

const LOADER_REQUEST = "LOADER_REQUEST";
const LOADER_SUCCESS = "LOADER_SUCCESS";

// Post

const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export {
  GET_POSTS_REQUEST,
  GET_POSTS_SUCCESS,
  GET_POSTS_FAIL,
  LOADER_REQUEST,
  LOADER_SUCCESS,
};
